rootProject.name = 'blink'

// 可以暂时注释掉不用的模块 提高编译速度
include 'blink-base:blink-base-app'
include 'blink-base:blink-base-api'
include 'blink-gateway-reactive'

include 'blink-framework-common'
include 'blink-web-starter'
//include 'blink-datasource-starter'
//include 'blink-framework-openfeign'
include 'blink-redis-starter'
//include 'blink-framework-validation'
//include 'blink-framework-mq'
//include 'gateway-admin'

