
// 1. 插件版本管理（Gradle 7+ 推荐使用 pluginManagement 集中管理插件版本）
pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        // spring插件专属仓库
        maven { url 'https://repo.spring.io/plugins-release/' }

    }
    plugins {
        id 'java'
        id 'idea'
        id 'maven-publish'
        id 'java-library'
        id 'io.spring.dependency-management' version '1.1.4'
        id 'org.springframework.boot' version '3.2.7'
    }
}


rootProject.name = 'blink'

// 可以暂时注释掉不用的模块 提高编译速度
include 'blink-base'
include 'blink-gateway:blink-gateway-reactive'

include 'blink-framework-common'
include 'blink-web-starter'
include 'blink-datasource-starter'
// include 'blink-framework-openfeign'
include 'blink-redis-starter'
//include 'blink-framework-validation'
//include 'blink-framework-mq'
include 'blink-log-starter'
include 'blink-gateway:gateway-admin'
include 'blink-base:blink-base-api-dubbo'
include 'blink-base:blink-base-app'
// include 'blink-base:blink-base-api'
//findProject(':blink-base:blink-base-api-dubbo')?.name = 'blink-base-api-dubbo'
findProject(':blink-gateway:blink-gateway-reactive')?.name = 'blink-gateway-reactive'
findProject(':blink-gateway:gateway-admin')?.name = 'gateway-admin'
include 'blink-gateway:blink-gateway-admin-api-dubbo'
findProject(':blink-gateway:blink-gateway-admin-api-dubbo')?.name = 'blink-gateway-admin-api-dubbo'

