pluginManagement {
    plugins {
        // 在此块内为每个需要用到的插件定义版本
        id 'org.springframework.boot' version '3.0.8'
        id 'io.spring.dependency-management' version '1.1.4'
    }
}

rootProject.name = 'blink'

// 可以暂时注释掉不用的模块 提高编译速度
include 'blink-base:blink-base-app'
include 'blink-base:blink-base-api'

include 'blink-framework-common'
include 'blink-web-starter'
include 'blink-datasource-starter'
include 'blink-framework-openfeign'
include 'blink-redis-starter'
include 'blink-framework-validation'
//include 'blink-framework-mq'
//include 'blink-framework-test'

include 'blink-gateway-reactive'
//include 'blink-gateway'
//include 'blink-stream'
//include 'blink-batch'
//include 'blink-framework-transaction'

