spring:
  cloud:
#    nacos:
#      ## 配置文件中心
#      config:
#        namespace: 94984ad7-b510-4ca4-bdcb-b6cdbd437dfb
#        server-addr: 127.0.0.1:8848
#        extension-configs:
#          - data-id: blink-gateway.yaml
#            group: DEFAULT_GROUP
#            refresh: true
#      ## 服务发现注册
#      discovery:
#        namespace: 94984ad7-b510-4ca4-bdcb-b6cdbd437dfb
#        enabled: true
#        server-addr: 127.0.0.1:8848
    loadbalancer:
      nacos:
        enabled: true
    gateway:
      metrics:
        enabled: true # 默认即为 true，确保开启
        tags:
          path:
            enabled: true # 强烈建议开启，为指标添加请求路径标签
      # 全局默认过滤器，对所有路由生效
#      default-filters:
#        - name: RequestRateLimiter
#          args:
##            rate-limiter: "#{@blinkRedisRateLimiter}"
#            redis-rate-limiter.replenishRate: 1  # 令牌桶每秒填充速率
#            redis-rate-limiter.burstCapacity: 2  # 令牌桶总容量
#            key-resolver: "#{@ipKeyResolver}"      # 限流维度解析器
#            redis-rate-limiter.includeHeaders: true
      # 确保多个网关实例路由同步
      #      discovery:
      #        locator:
      #          enabled: true

      httpclient:
        connect-timeout: 10000
        response-timeout: 5s
        #动态路由 由配置中心json配置
      routes:
        - id: base-app
          uri: lb://base-app
          predicates:
            - Path=/base/**
          filters:
             # 1. 先限流
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            # 2. 再重试
            - name: Retry
              args:
                retries: 2
            # 3. 最后熔断
            - name: CircuitBreaker
              args:
                name: protectedCircuitBreaker
                # 不配置 让异常抛出 由全局异常处理
#                fallbackUri: forward:/fallback/default
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 0 # 数据库索引
      lettuce:
        pool:
          max-active: 8 # 连接池最大活跃连接数（使用负值表示没有限制）
          max-idle: 8 # 连接池最大空闲连接数
          max-wait: -1ms # 连接池最大阻塞等待时间 毫秒（使用负值表示没有限制）
          min-idle: 0 # 最小空闲连接数


# actuator 监控
management:
  server:
    port: 8003
  endpoints:
    web:
      exposure:
        include: "*" # 暴露所有端点，生产环境建议按需暴露
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
      circuitbreakers:
        enabled: true
      ratelimiters:
        enabled: true
    metrics:
      export:
        prometheus:
          enabled: true

#blink:
#  gateway:
#    configDataId: gateway-routes
#    configGroup: DEFAULT_GROUP
#    localCacheEnable: true
#    eventStreamEnable: false
#    dynamicRoute:
#      mode: close
#      nacos:
#        dataId: gateway-routes
#        group: DEFAULT_GROUP
##      redis:
##        routeSuffix: default
##        groupId: route-consumer-1
##        streamkey: blink:stream:gateway:route
#    ingnoredUrl:
#      - /login
#      - /captcha/get
#    instance-id: 00
#
#  redis:
#    enableLocalCache: false
#    idGenerator:
#      seq-param:
#        request:
#          step: 1000
#          fetch-percent: 0.8
#        trance:
#          step: 2000

