plugins {
    id 'org.springframework.boot'

}

jar {
    enabled = true
    bootJar.enabled = false
    // 消除 打的包带 plain
    archiveClassifier = ''
    manifest {
        attributes('Implementation-Title': 'Gradle',
                'Implementation-Version': archiveVersion)
    }
}


dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-logging'
    implementation 'org.springframework.boot:spring-boot-starter-aop'
    implementation 'org.springframework.boot:spring-boot-starter-amqp'

    implementation "com.alibaba.fastjson2:fastjson2:${fastjson2Extension}"
    implementation "com.alibaba.fastjson2:fastjson2-extension-spring6:${fastjson2Extension}"

    implementation 'com.blink:blink-dataSource-spring-boot-starter:1.0.0-SNAPSHOT'
    implementation 'com.blink:blink-framework-common:1.0.0-SNAPSHOT'

    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

}

// 打包sourcesJar任务
task sourcesJar(type: Jar, dependsOn: classes) {
    archiveClassifier = 'sources'
    from sourceSets.main.allSource
}

publishing {
    publications {
        library(MavenPublication) {
            groupId = project.group
            artifactId = project.name
            version = project.version

            from components.java
            artifact sourcesJar
        }
    }

    repositories {
        maven {
            allowInsecureProtocol true
            url "http://localhost:8081/repository/maven-snapshots/"
            credentials {
                username 'admin'
                password '123456'
            }
        }

    }
}

//
//tasks.named('test') {
//    useJUnitPlatform()
//}
