plugins {
    id 'org.springframework.boot'

}

jar {
    enabled = true
    bootJar.enabled = false
    // 消除 打的包带 plain
    archiveClassifier = ''
    manifest {
        attributes('Implementation-Title': 'Gradle',
                'Implementation-Version': archiveVersion)
    }
}


dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-logging'
    implementation 'org.springframework.boot:spring-boot-starter-aop'
    implementation 'org.springframework.boot:spring-boot-starter-amqp'


    implementation 'com.blink:blink-dataSource-spring-boot-starter:1.0.0-SNAPSHOT'
    implementation 'com.blink:blink-framework-common:1.0.0-SNAPSHOT'

    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

}

//
//tasks.named('test') {
//    useJUnitPlatform()
//}
