plugins {
    id 'org.springframework.boot'
}



dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'com.github.seancfoley:ipaddress:5.5.1'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'cn.hutool:hutool-core'

    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jdk8'
    implementation 'com.fasterxml.jackson.module:jackson-module-parameter-names'

}

// 任务：生成源码JAR
java {
    withSourcesJar()
    modularity.inferModulePath = true
}

jar {
    enabled = true
    // 消除 打的包带 plain
    archiveClassifier = ''
    manifest {
        attributes('Implementation-Title': 'Gradle',
                'Implementation-Version': archiveVersion)
    }
}

tasks.named('jar') {
    // 设置JAR包的manifest属性
    manifest {
        attributes('Automatic-Module-Name': project.name)
        // 如果需要，你也可以在这里指定主类 (Main-Class)
        // attributes('Main-Class': 'com.yourcompany.yourmodule.MainClass')
    }

    // 确保包含所有必要的资源文件
    include 'META-INF/**'
    include '**/*.class' // 这行通常可以省略，因为jar任务默认包含编译输出的class文件
}

// 任务：生成Javadoc JAR
//tasks.register('javadocJar', Jar) {
//    archiveClassifier = 'javadoc'
//    from javadoc
//}




tasks.named('test') {
    useJUnitPlatform()
}
