plugins {
    id 'org.springframework.boot'
}



dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'com.github.seancfoley:ipaddress:5.5.1'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'cn.hutool:hutool-core'

    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jdk8'
    implementation 'com.fasterxml.jackson.module:jackson-module-parameter-names'

    //jwt 开源库
    implementation "io.jsonwebtoken:jjwt-api:${jjwtVersion}"
    runtimeOnly "io.jsonwebtoken:jjwt-impl:${jjwtVersion}"
    runtimeOnly "io.jsonwebtoken:jjwt-jackson:${jjwtVersion}"

    //能够读取源码javadoc注释的库
    annotationProcessor 'com.github.therapi:therapi-runtime-javadoc-scribe:0.15.0'
    // Runtime library
    implementation 'com.github.therapi:therapi-runtime-javadoc:0.13.0'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

// 任务：生成源码JAR
java {
    withSourcesJar()
    modularity.inferModulePath = true
}

jar {
    enabled = true
    archiveClassifier = ''
}

bootJar {
    enabled = false
}

springBoot {
    mainClass = null
}

// 禁用resolveMainClassName任务，因为这是一个库模块，不需要主类
tasks.named('resolveMainClassName').configure {
    enabled = false
}

tasks.named('jar') {
    // 设置JAR包的manifest属性
    manifest {
        attributes('Automatic-Module-Name': project.name)
        // 如果需要，你也可以在这里指定主类 (Main-Class)
        // attributes('Main-Class': 'com.yourcompany.yourmodule.MainClass')
    }

    // 确保包含所有必要的资源文件
    include 'META-INF/**'
    include '**/*.class' // 这行通常可以省略，因为jar任务默认包含编译输出的class文件
}

// 任务：生成Javadoc JAR
//tasks.register('javadocJar', Jar) {
//    archiveClassifier = 'javadoc'
//    from javadoc
//}




tasks.named('test') {
    useJUnitPlatform()
}
