plugins {
    id 'org.springframework.boot'

}


// 任务：生成源码JAR
java {
    withSourcesJar()
    modularity.inferModulePath = true
}

jar {
    enabled = true
    archiveClassifier = ''
}

bootJar {
    enabled = false
}


publishing {
    publications {
        mavenJava(MavenPublication) {
            // 也可以单独指定 groupId, artifactId, version，如果未指定，则使用项目默认的
            groupId = 'com.blink'
            artifactId = 'blink-dataSource-spring-boot-starter'
            version = '1.0.0-SNAPSHOT'
        }
    }
}

dependencies {

    implementation "com.baomidou:mybatis-plus-generator:${mybatisPlusVersion}"
    api("com.baomidou:mybatis-plus-spring-boot3-starter:${mybatisPlusVersion}")
    implementation "com.mysql:mysql-connector-j:${mysqlConnectorVersion}"
    implementation "com.alibaba:druid-spring-boot-starter:${druidStarterVersion}"
    implementation "com.github.pagehelper:pagehelper:${pagehelperVersion}"
    implementation 'org.apache.velocity:velocity:1.7'
    implementation 'cn.hutool:hutool-core'

    implementation 'com.blink:blink-framework-common:1.0.0-SNAPSHOT'

    // ============ 测试框架 ============
    testImplementation 'com.blink:blink-framework-test:1.0.0-SNAPSHOT'
}


tasks.named('test') {
    useJUnitPlatform()
}
