plugins {

    id 'org.springframework.boot'
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}


dependencies {
    implementation 'org.springframework.cloud:spring-cloud-starter-gateway'
    implementation 'org.springframework.cloud:spring-cloud-starter-bootstrap'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis-reactive'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.cloud:spring-cloud-starter-loadbalancer'
    implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery'
    implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config'

    implementation 'org.springframework.cloud:spring-cloud-starter-circuitbreaker-reactor-resilience4j'
    implementation 'io.github.resilience4j:resilience4j-spring-boot3'
    implementation 'io.github.resilience4j:resilience4j-circuitbreaker'
//    implementation 'io.github.resilience4j:resilience4j-ratelimiter'
    implementation 'io.github.resilience4j:resilience4j-retry'
    implementation 'io.github.resilience4j:resilience4j-bulkhead'



    //ip地址处理库
    implementation 'com.github.seancfoley:ipaddress:5.5.1'
    //本地缓存
    implementation "com.github.ben-manes.caffeine:caffeine:${caffeineVersion}"

    //工具类
    implementation 'cn.hutool:hutool-core'
    implementation 'cn.hutool:hutool-jwt'
    implementation 'io.micrometer:micrometer-registry-prometheus'
//    implementation 'cn.hutool:hutool-crypto'

    implementation 'com.blink:blink-framework-common:1.0.0-SNAPSHOT'
    implementation 'com.blink:blink-framework-validation:1.0.0-SNAPSHOT'
    implementation 'com.blink:blink-redis-spring-boot-starter:1.0.0-SNAPSHOT'
    //在reactive 环境中 无法使用openfeign 用webclient代替
    implementation('com.blink:blink-base-api:1.0.0-SNAPSHOT') {
        // 排除指定 group 和 module 的传递依赖
        exclude group: 'com.blink', module: 'blink-framework-openfeign'
    }


    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
//    developmentOnly 'org.springframework.boot:spring-boot-devtools'

}



tasks.named('test') {
    useJUnitPlatform()
}
